### ISSUE TITLE
The H4 cell in k1 sheet of Chapter3-1a.xlsx

### ISSUE THREAD

**Issue by paicheng** [hhohho/Learn-Data-Mining-through-Excel#1]
The `H4` cell in `k1 sheet` of `Chapter3-1a.xlsx` should be 15, not 1.5.
The `K6` cell should be 40, not 50.

**Comment by hhohho** [comment]
Thank you, paicheng! I typed in those numbers in my last round of proof-read, should do copy/paste.

Good job and appreciate it.

**Comment by paicheng** [comment]
很高興能幫上忙。
